### ISSUE TITLE
jboss-classfilewriter don't include the license file

### ISSUE THREAD

**Issue by puntogil** [jbossas/jboss-classfilewriter#11]
Hi

Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
Thanks in advance
Regards

**Comment by puntogil** [comment]
There is another problem with the file README is empty or broken.
Please, can You remove of fix it?
Regards

**Comment by ropalka** [comment]
License fixed with https://github.com/jbossas/jboss-classfilewriter/commit/8bc34bb56a96c1bbe2d63baed325c89a2e0371f5
