### ISSUE TITLE
ConstPool is limited to 32767 entries

### ISSUE THREAD

**Issue by mkouba** [jbossas/jboss-classfilewriter#12]
Is there a reason to limit the size of a constant pool to `short`, i.e. 32767? According to JVM the constant pool is limited to 65535 entries. See also http://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.11.

**Comment by mkouba** [comment]
Maybe we should also add a check whether a `constPoolSize` exceeds the limit?

**Comment by mkouba** [comment]
That was quick, thanks! ;-)

**Comment by stuartwdouglas** [comment]
Do you need a release with this?

**Comment by mkouba** [comment]
It seems `org.jboss.classfilewriter.code.CodeAttribute.writeShort(int)` should probably only fail if `n > Short.MAX_VALUE * 2`.

By the way, https://github.com/jbossas/jboss-classfilewriter/commit/b2eb9f0ae93bb1f911ccfb35146f5dd84458ea3f breaks weld on few places. `org.jboss.classfilewriter.code.CodeAttribute.anewarray(String)` previously accepted a class name, e.g. `java.lang.Class`. Now it fails with:

```
Caused by: java.lang.RuntimeException: invalid descriptor [Ljava.lang.Class;
	at org.jboss.classfilewriter.code.StackEntry.<init>(StackEntry.java:68)
	at org.jboss.classfilewriter.code.StackEntry.of(StackEntry.java:115)
	at org.jboss.classfilewriter.code.StackState.push(StackState.java:93)
	at org.jboss.classfilewriter.code.StackFrame.replace(StackFrame.java:138)
	at org.jboss.classfilewriter.code.CodeAttribute.anewarray(CodeAttribute.java:233)
```

**Comment by mkouba** [comment]
The same applies to `org.jboss.classfilewriter.code.CodeAttribute.exceptionBlockStart(String)` and maybe other methods...

A simple fix is to do `type.replace('.', '/')` on a param but it might deserve a more systematic approach :-).

**Comment by mkouba** [comment]
@stuartwdouglas Thanks again :-)
