### ISSUE TITLE
CFW is using Unsafe to define classes which fails on Java 11

### ISSUE THREAD

**Issue by dmlloyd** [jbossas/jboss-classfilewriter#16]
Java 11 has deleted the Unsafe.defineClass method.  Instead of using this method, we could use an alternative strategy:

* Reflectively access ``ClassLoader.defineClass`` (maybe using Unsafe to toggle the accessibility flag)
* When running with a JBoss Modules class loader (1.9 or later), use ``org.jboss.modules.ClassDefiner`` to define generated classes
* Some other option?

**Comment by dmlloyd** [comment]
https://ci.wildfly.org/viewLog.html?buildId=103413&tab=buildResultsDiv&buildTypeId=WF_MasterLinuxJdk11

**Comment by manovotn** [comment]
Hmm, I recall mailing Stuart about this change in early April and he said that using `Unsafe` to crack open `CL.defineClass()` didn't work for classfilewriter. I wonder what the problem was.

**Comment by manovotn** [comment]
Actually I just tried the approach and it seems to work for me but I may be missing something obvious.
Sent a PR.

**Comment by rsvoboda** [comment]
I guess this can be closed now.
